# Generated by Django 6.1 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='پرسش')),
                ('answer', models.TextField(blank=True, default='', verbose_name='پاسخ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('generating', 'در حال تولید'), ('done', 'پاسخ داده شده'), ('failed', 'ناموفق')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='منابع')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
