# Generated by Django 6.1 on 2026-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=models.CharField(choices=[('none', 'بدون بازخورد'), ('up', 'پاسخ مفید بود'), ('down', 'پاسخ مفید نبود')], default='none', max_length=4, verbose_name='بازخورد'),
        ),
    ]
