# Generated by Django 6.1 on 2026-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='demo_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='شناسه دمو'),
        ),
    ]
