# Generated by Django 6.1 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='فایل')),
                ('full_text', models.TextField(blank=True, default='', verbose_name='متن کامل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('ready', 'آماده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-created_at'],
            },
        ),
    ]
